### ISSUE TITLE
auth.create_user() not using application default credentials, gives 403

### ISSUE THREAD

**Issue by crunk1** [firebase/firebase-admin-python#138]
### Environment

  * Operating System version: Win 10
  * Python version: 3.6.4
  * Firebase SDK version: firebase-admin 2.9.0
  * Library version: 2.9.0
  * Firebase Product: auth

### Problem description
I'm trying to create a user with `firebase_admin.auth.create_user(email=email, app=app)` in a dev environment on my local machine. I initialize `app` with 
`app = firebase_admin.initialize_app(options={'projectId': 'DEVPROJECT'})`

Output:
```
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\firebase_admin\_user_mgt.py", line 289, in create_user
    response = self._request('post', 'signupNewUser', json=payload)
  File "C:\Python36\lib\site-packages\firebase_admin\_user_mgt.py", line 384, in _request
    resp.raise_for_status()
  File "C:\Python36\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\firebase_admin\auth.py", line 249, in create_user
    uid = user_manager.create_user(**kwargs)
  File "C:\Python36\lib\site-packages\firebase_admin\_user_mgt.py", line 291, in create_user
    self._handle_http_error(USER_CREATE_ERROR, 'Failed to create new user.', error)
  File "C:\Python36\lib\site-packages\firebase_admin\_user_mgt.py", line 348, in _handle_http_error
    raise ApiCallError(code, msg, error)
firebase_admin._user_mgt.ApiCallError: Failed to create new user.
Server response: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. Google Identity Toolkit API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://conso
le.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the ac
tion to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. Google Identity Toolkit API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console
.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the acti
on to propagate to our systems and retry."
 }
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Scott\workspace\onechart-gae\app\tests\dev\patients_test.py", line 12, in setUpClass
    super(PatientTests, cls).setUpClass()
  File "C:\Users\Scott\workspace\onechart-gae\app\tests\dev\__init__.py", line 20, in setUpClass
    cls.u1 = db.Users.get_or_create('tester1@test.onecharthealth.com')
  File "C:\Users\Scott\workspace\onechart-gae\app\db\users.py", line 44, in get_or_create
    u = firebase.get_or_create_user(email, create_password)
  File "C:\Users\Scott\workspace\onechart-gae\app\firebase.py", line 45, in get_or_create_user
    return firebase_admin.auth.create_user(email=email, app=app)
  File "C:\Python36\lib\site-packages\firebase_admin\auth.py", line 252, in create_user
    raise AuthError(error.code, str(error), error.detail)
firebase_admin.auth.AuthError: Failed to create new user.
Server response: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. Google Identity Toolkit API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://conso
le.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the ac
tion to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. Google Identity Toolkit API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console
.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the acti
on to propagate to our systems and retry."
 }
}
```

#### Code to repro:

```
# First, init your application default creds with `gcloud auth application-default login`
import firebase_admin
import firebase_admin.auth

PROJECTID = 'YOURPROJECT'


def main():
    app = firebase_admin.initialize_app(options={'projectId': PROJECTID})
    
    u = firebase_admin.auth.create_user(email='test@example.com', app=app)
    print(u)


if __name__ == '__main__':
    main()
```

**Comment by crunk1** [comment]
Related: https://github.com/firebase/friendlychat-web/issues/252

**Comment by crunk1** [comment]
It should be noted that project 764086051850 != my dev project. I've seen similar problems where the library requires a service account credentials file.

**Comment by hiranya911** [comment]
When running locally you must set up application default credentials (ADC) by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. That's the only way to make this scenario work.

Identity toolkit backend API identifies the project based on the credential and credential only. When you use ADC locally without setting the environment variable, it will default to whatever project configured with the gcloud SDK.

**Comment by hiranya911** [comment]
It might also work if you just set the correct project in your gcloud config:

`gcloud config set project <MY_PROJECT_ID>`

**Comment by crunk1** [comment]
"Identity toolkit backend API identifies the project based on the credential and credential only."

I thought that would be the response. Do we have anything in the works to change that? Or is there a reason why we aren't?

**Comment by hiranya911** [comment]
The credential is sufficient to identify the project. You can (and should) continue to use Application Default Credentials (ADC) for this scenario, but when testing locally you must set up ADC via the [environment variable](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application). When deployed to the cloud (App Engine, Compute Engine), no service account file is needed and it will just work. 

There is probably a bug here where the backend API ignores the project ID set locally via the `gcloud` SDK (I tested this since my last comment, and no joy). It always defaults to 764086051850, whatever that is. I've created an internal bug for the Auth team to track that.

```
>>> import firebase_admin
>>> from firebase_admin import auth
>>> app = firebase_admin.initialize_app()
>>> app.credential.project_id
'xxxxxxxx-xx' # Prints the project ID set via gcloud SDK
>>> auth.get_user('foo')
Traceback (most recent call last):
  File "/Users/hkj/Projects/ml/env/lib/python3.6/site-packages/firebase_admin/_user_mgt.py", line 241, in get_user
    response = self._request('post', 'getAccountInfo', json=payload)
  File "/Users/hkj/Projects/ml/env/lib/python3.6/site-packages/firebase_admin/_user_mgt.py", line 372, in _request
    resp.raise_for_status()
  File "/Users/hkj/Projects/ml/env/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hkj/Projects/ml/env/lib/python3.6/site-packages/firebase_admin/auth.py", line 117, in get_user
    response = user_manager.get_user(uid=uid)
  File "/Users/hkj/Projects/ml/env/lib/python3.6/site-packages/firebase_admin/_user_mgt.py", line 244, in get_user
    self._handle_http_error(INTERNAL_ERROR, msg, error)
  File "/Users/hkj/Projects/ml/env/lib/python3.6/site-packages/firebase_admin/_user_mgt.py", line 336, in _handle_http_error
    raise ApiCallError(code, msg, error)
firebase_admin._user_mgt.ApiCallError: Failed to get user by user ID: foo.
Server response: {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. Google Identity Toolkit API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. Google Identity Toolkit API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/identitytoolkit.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 }
} 
```

Notice the 764086051850 in the error, which is what you got as well. And the API has ignored the project ID set on the default credential. Hopefully, the Auth team will fix this, and then you will be able to avoid having to set the environment variable.

**Comment by hiranya911** [comment]
It turns out 764086051850 is a special project associated with the gcloud SDK itself. You will find this configured in the `client_id` field of `~/.config/gcloud/application_default_credentials.json` (on Mac and Linux). When no service account is configured locally, the ADC obtains a token that is actually attached to this project. I don't think there's much the backend Auth team can do here, unless they decide to support specifying project ID via some other means.
