### ISSUE TITLE
`!('TopicA' in topics)`  condition does not work.

### ISSUE THREAD

**Issue by ton-katsu** [firebase/firebase-admin-python#145]
### Environment

Operating System version: macOS 10.13.3
Firebase SDK version: firebase_admin 2.9.1
Firebase Product: messaging
Python version: 3.6.2

#### Steps to reproduce:

`!('TopicA' in topics)`  condition does not work.
https://firebase.google.com/docs/cloud-messaging/ios/topic-messaging#build_send_requests

`'TopicA' in topics` worked.

I tried nodejs `https://github.com/firebase/firebase-admin-node`.  worked.

#### Relevant Code:

```
try:
    data = {
        "title" : "test",
        "body" : "great match"
    }
    notification = messaging.Notification(title="test", body=None)
    condition = "!('TopicA' in topics)"
    message = messaging.Message(data=data, notification=notification, condition=condition)
    res = messaging.send(message)
    print(res)
except Exception as e:
    print(e)
    print(traceback.print_exc())
```

##### error

```
Request contains an invalid argument.
Traceback (most recent call last):
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/firebase_admin/messaging.py", line 764, in send
    resp = self._client.body('post', url=self._fcm_url, json=data, timeout=self._timeout)
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/firebase_admin/_http_client.py", line 93, in body
    resp = self.request(method, url, **kwargs)
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/firebase_admin/_http_client.py", line 85, in request
    resp.raise_for_status()
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fcm.googleapis.com/v1/projects/dev-leahi-gcp/messages:send

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "firebase.py", line 47, in a
    res = messaging.send(message, app=app)
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/firebase_admin/messaging.py", line 54, in send
    return _get_messaging_service(app).send(message, dry_run)
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/firebase_admin/messaging.py", line 767, in send
    self._handle_fcm_error(error)
  File "/Users/x/.anyenv/envs/pyenv/versions/3.6.2/lib/python3.6/site-packages/firebase_admin/messaging.py", line 826, in _handle_fcm_error
    raise ApiCallError(code, msg, error)
firebase_admin.messaging.ApiCallError: Request contains an invalid argument.
```

**Comment by hiranya911** [comment]
Known issue in the FCM HTTP v1 API. FCM backend team is working on it. Nothing that can be fixed in this codebase.

**Comment by wrinkl3** [comment]
Just hit the same problem. Has this been solved or at least side-stepped?

**Comment by ourcoteam** [comment]
Is there any update ?!
