### ISSUE TITLE
test execution via ``setup.py test'' fails without attempting to run pytest runner

### ISSUE THREAD

**Issue by ncouture** [firebase/firebase-admin-python#155]
Python 3 incompatible code was introduced in  #130 and is causing test execution to fail in this environment:
```shell
$ python setup.py test
running test
running egg_info
writing firebase_admin.egg-info/PKG-INFO
writing dependency_links to firebase_admin.egg-info/dependency_links.txt
writing requirements to firebase_admin.egg-info/requires.txt
writing top-level names to firebase_admin.egg-info/top_level.txt
reading manifest file 'firebase_admin.egg-info/SOURCES.txt'
writing manifest file 'firebase_admin.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    'License :: OSI Approved :: Apache Software License',
  File "/home/user/.local/share/virtualenvs/utils-iX9zXjhl/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/.local/share/virtualenvs/utils-iX9zXjhl/lib/python3.7/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/home/user/.local/share/virtualenvs/utils-iX9zXjhl/lib/python3.7/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/local/lib/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/local/lib/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/local/lib/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 347, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/local/lib/python3.7/unittest/loader.py", line 404, in _find_tests
    full_path, pattern, namespace)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 481, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/user/.local/share/virtualenvs/utils-iX9zXjhl/lib/python3.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/lib/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/user/.local/share/virtualenvs/utils-iX9zXjhl/lib/python3.7/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/user/firebase-admin-python/snippets/database/index.py", line 35
    print ref.get()
            ^
SyntaxError: invalid syntaex
```

**Comment by ncouture** [comment]
This issue is bogus and due to my attempt to run tests via setup.py.

I created a PR but the changes are unnecessary aside for preventing user confusion.

**Comment by hiranya911** [comment]
FTR instructions for running tests are in also in the CONTRIBUTING.md file
