### ISSUE TITLE
ImportError: No module named firebase_admin on GAE

### ISSUE THREAD

**Issue by linhtx** [firebase/firebase-admin-python#164]
* Operating System version: Google app engine standard
  * Firebase SDK version: 2.10.0
  * Python version: 2.7
  * Firebase Product: user authentication

I use Python 2.7, virtualenv, google app engine standard and firebase-admin.
When I run app on Google app engine dev and production environment, i have met error console "ImportError: No module named firebase_admin". Even firebase-admin be installed.
<img width="315" alt="screen shot 2018-05-16 at 10 29 37 am" src="https://user-images.githubusercontent.com/5160691/40102436-b4149fc2-5914-11e8-8428-c1f05a517beb.png">

Console output: 
```
Traceback (most recent call last):
  File "/Users/mac/store/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Users/mac/store/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Users/mac/store/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/mac/store/source/gae/main.py", line 3, in <module>
    import firebase_admin
ImportError: No module named firebase_admin
```
<img width="569" alt="screen shot 2018-05-16 at 10 30 08 am" src="https://user-images.githubusercontent.com/5160691/40102452-bec25414-5914-11e8-953e-f8d35f85b2f0.png">

Issue only meets with GAE. If i run normally: python main.py, it still works.
Please help me to give suggestion!

**Comment by linhtx** [comment]
Thanks @hiranya911 for your support, this issue be fixed.
Currently, i have met issue: https://github.com/firebase/firebase-admin-python/issues/166

Please help me to suggest!
