### ISSUE TITLE
auth.verify_id_token unexpected max_retries

### ISSUE THREAD

**Issue by Fandekasp** [firebase/firebase-admin-python#177]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Docker
  * Firebase SDK version: python-firebase==1.2
  * Library version: firebase-admin==2.9.0
  * Firebase Product: auth

#### Steps to reproduce:

* send a request with the X-TOKENID header containing a firebase id token.
* use code below as default authentication class within a project using djangorestframework
    ```py
    REST_FRAMEWORK = {
         'DEFAULT_AUTHENTICATION_CLASSES': [
             'app.authentication.FirebaseAuthentication',
         ]
    }
    ```
* When the code reaches the function call `auth.verify_id_token(token)`, the error below is returned
```
in FirebaseAuthentication.authenticate                                                                                                                                                 
Internal Server Error: /api/users/2/                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                     
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner                                                                                   
    response = get_response(request)                                                                                                                                                  
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response                                                                              
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/src/django-rest-framework/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/src/django-rest-framework/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)                          
  File "/src/django-rest-framework/rest_framework/views.py", line 443, in handle_exception                                                                                            
    self.raise_uncaught_exception(exc)
  File "/src/django-rest-framework/rest_framework/views.py", line 471, in dispatch
    self.initial(request, *args, **kwargs)
  File "/src/django-rest-framework/rest_framework/views.py", line 388, in initial                                                                                                      
    self.perform_authentication(request)                                                                                                                                               
  File "/src/django-rest-framework/rest_framework/views.py", line 314, in perform_authentication                                                                                       
    request.user                                                                                                                                                                       
  File "/src/django-rest-framework/rest_framework/request.py", line 222, in user                                                                                                       
    self._authenticate()                                                                                                                                                               
  File "/src/django-rest-framework/rest_framework/request.py", line 375, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)                           
  File "/code/app/authentication.py", line 30, in authenticate                   
    firebase_user = auth.verify_id_token(token)
  File "/usr/local/lib/python3.6/site-packages/firebase_admin/auth.py", line 103, in verify_id_token
    token_generator = _get_auth_service(app).token_generator
  File "/usr/local/lib/python3.6/site-packages/firebase_admin/auth.py", line 58, in _get_auth_service
    return _utils.get_app_service(app, _AUTH_ATTRIBUTE, _AuthService)
  File "/usr/local/lib/python3.6/site-packages/firebase_admin/_utils.py", line 35, in get_app_service
    return app._get_service(name, initializer) # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/site-packages/firebase_admin/__init__.py", line 297, in _get_service
    self._services[name] = initializer(self)
  File "/usr/local/lib/python3.6/site-packages/firebase_admin/auth.py", line 847, in __init__
    self._user_manager = _user_mgt.UserManager(app)
  File "/usr/local/lib/python3.6/site-packages/firebase_admin/_user_mgt.py", line 230, in __init__
    session = transport.requests.AuthorizedSession(g_credential)
  File "/usr/local/lib/python3.6/site-packages/google/auth/transport/requests.py", line 172, in __init__
    retry_adapter = requests.adapters.HTTPAdapter(max_retries=3)
TypeError: __init__() got an unexpected keyword argument 'max_retries'
```

#### Relevant Code:

```py
from rest_framework.authentication import BaseAuthentication
from rest_framework import exceptions
import firebase_admin
from firebase_admin import credentials, auth
import logging
from .models import User
from django.conf import settings

logger = logging.getLogger('django')

credentials = credentials.Certificate(
    settings.FIREBASE_AUTH['FIREBASE_ACCOUNT_KEY_FILE'],
)
firebase_admin.initialize_app(credentials)


class FirebaseAuthentication(BaseAuthentication):
    """Authenticate the user and get its info from Firebase.

    The token is sent in the request as idToken and verified with
    the Firebase admin.
    """

    def authenticate(self, request):
        """Actual authentication happens here."""
        logger.info('in FirebaseAuthentication.authenticate')
        token = request.META.get('HTTP_X_TOKENID')
        if token:
            try:
                firebase_user = auth.verify_id_token(token)
            except ValueError:
                logger.info('verify_id_token ValueError "{}"'.format(token))
                return None
            if not firebase_user:
                logger.info('No firebase_user for token "{}"'.format(token))
                return None

            user_id = firebase_user.get('user_id')
            logger.info("firebase user id: {}".format(user_id))
            try:
                user = User.objects.get(id=user_id)
                logger.info('User found: id={}, email={}'.format(
                    user_id, user.email))
            except User.DoesNotExist:
                raise exceptions.AuthenticationFailed('No such user')
            return (user, None)
        else:
            # no token provided
            return None
```

**Comment by hiranya911** [comment]
This is the failing line of code (from `google-auth`): https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/transport/requests.py#L172

`max_retries` is indeed a parameter supported in `requests`: http://docs.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter

You're likely using an ancient version of `requests`, or your installation of `requests` in Django environment is broken some how.

**Comment by Fandekasp** [comment]
Indeed, my requests version was v1.1.0 O_O We're upgrading our packages on a weekly basis, so this kind of miss is unbelievable. Thanks for the reply @hiranya911
