### ISSUE TITLE
Firebase Auth TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by kwagdy** [firebase/firebase-admin-python#185]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.13.4
  * Library version: 2.12.0
  * Firebase Product: auth
  * Google App Launcher installed
  * Python 2.7 installed

### [REQUIRED] Step 3: Describe the problem

Getting the below error when using the auth module, _seems to be coming from `requests/adapters.py` library module_
```
File "/myAppPath/lib/requests/adapters.py", line 121, in __init__
    super(HTTPAdapter, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
```

#### Steps to reproduce:

1. Create a new Application from Google App Launcher (File -> New Application)
2. Follow the steps in [Using third-party libraries](https://cloud.google.com/appengine/docs/standard/python/tools/using-libraries-python-27) and create the file `appengine_config.py`
3. Install **firebase-admin** module in the folder called "lib" in your new app folder: pip install -t ~/myAppPath/lib firebase-admin
4. Install **requests** module in the folder called "lib" in your new app folder: pip install -t ~/myAppPath/lib requests
5. Install **requests-toolbelt** module in the folder called "lib" in your new app folder: pip install -t ~/myAppPath/lib requests-toolbelt (required as per your docs [Issuing HTTP(S) Requests](https://cloud.google.com/appengine/docs/standard/python/issue-requests#issuing_an_http_request))
6. Edit **app.yaml** to support the SSL library _see code below_
7. Edit your **main.py** file to use the firebase admin SDK  _see code below_

#### Relevant Code:
**app.yaml**
```
application: apptest01
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest
```

**main.py**
```
import webapp2
import requests_toolbelt.adapters.appengine
import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth

requests_toolbelt.adapters.appengine.monkeypatch()

myjson = {
  "type": "service_account",
  "project_id": "<your-project-id>",
  "private_key_id": "<your-key>",
  "private_key": "<your-private-key>",
  "client_email": "<your-client-email>",
  "client_id": "<your-client-id>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "<your-cert-url>"
}

cred = credentials.Certificate(myjson)
default_app = firebase_admin.initialize_app(cred)

class MainHandler(webapp2.RequestHandler):
    def get(self):
        self.response.write('Hello world!')
        #Any function using the auth module will result in the same error
        print "User:", auth.get_user_by_phone_number("+20123456789")

app = webapp2.WSGIApplication([
    ('/', MainHandler)
], debug=True)
```

**Error Log**
```
>>> Started..
User:/myAppPath/apptest01/lib/urllib3/contrib/appengine.py:115: AppEnginePlatformWarning: urllib3 is using URLFetch on Google App Engine sandbox instead of sockets. To use sockets directly instead of URLFetch see https://urllib3.readthedocs.io/en/latest/reference/urllib3.contrib.html.
  AppEnginePlatformWarning)
ERROR    2018-07-30 22:59:50,291 webapp2.py:1552] super(type, obj): obj must be an instance or subtype of type
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/myAppPath/apptest01/main.py", line 45, in get
    print "User:", auth.get_user_by_phone_number("+20123456789")
  File "/myAppPath/apptest01/lib/firebase_admin/auth.py", line 273, in get_user_by_phone_number
    user_manager = _get_auth_service(app).user_manager
  File "/myAppPath/apptest01/lib/firebase_admin/auth.py", line 95, in _get_auth_service
    return _utils.get_app_service(app, _AUTH_ATTRIBUTE, _AuthService)
  File "/myAppPath/apptest01/lib/firebase_admin/_utils.py", line 35, in get_app_service
    return app._get_service(name, initializer) # pylint: disable=protected-access
  File "/myAppPath/apptest01/lib/firebase_admin/__init__.py", line 295, in _get_service
    self._services[name] = initializer(self)
  File "/myAppPath/apptest01/lib/firebase_admin/auth.py", line 473, in __init__
    self._token_verifier = _token_gen.TokenVerifier(app)
  File "/myAppPath/apptest01/lib/firebase_admin/_token_gen.py", line 226, in __init__
    session = cachecontrol.CacheControl(requests.Session())
  File "/myAppPath/apptest01/lib/cachecontrol/wrapper.py", line 24, in CacheControl
    cacheable_methods=cacheable_methods,
  File "/myAppPath/apptest01/lib/cachecontrol/adapter.py", line 26, in __init__
    super(CacheControlAdapter, self).__init__(*args, **kw)
  File "/myAppPath/apptest01/lib/requests/adapters.py", line 121, in __init__
    super(HTTPAdapter, self).__init__()
TypeError: super(type, obj): obj must be an instance or subtype of type
INFO     2018-07-30 22:59:50,314 module.py:812] default: "GET / HTTP/1.1" 500 3831```

**Comment by kwagdy** [comment]
The problem was that I have misplaced the `requests_toolbelt.adapters.appengine.monkeypatch` line in my code. I don't remember why it was moved down after importing firebase and credentials and auth. But for some reason it was moved down thus causing the error to happen.

**The wrong placement:**

```
import webapp2

import requests_toolbelt.adapters.appengine

from firebase_admin import credentials
from firebase_admin import auth
import firebase_admin

cred = credentials.Certificate(myjson)
default_app = firebase_admin.initialize_app(cred)

requests_toolbelt.adapters.appengine.monkeypatch() # <-- wrong placement!
```
**The correct placement:**

```
import webapp2

import requests_toolbelt.adapters.appengine
requests_toolbelt.adapters.appengine.monkeypatch() # <-- correct placement!

from firebase_admin import credentials
from firebase_admin import auth
import firebase_admin

cred = credentials.Certificate(myjson)
default_app = firebase_admin.initialize_app(cred)
```
