### ISSUE TITLE
'AuthorizedSession' object has no attribute 'credentials'

### ISSUE THREAD

**Issue by hoonk** [firebase/firebase-admin-python#197]
Step 2:

  * Operating System version: GAE Standard Environment Python
  * Firebase SDK version: Firebase Admin SDK 2.13
  * Firebase Product: Database

Step 3: Describe the problem

It is not consistent, but on deferred tasks to update my Firebase Realtime Database, I see errors with the message: `'AuthorizedSession' object has no attribute 'credentials'`

The strange thing is that it's not consistent.  Sometimes it happens, sometimes not.

#### Steps to reproduce:

Here's the output from the logs

```
'AuthorizedSession' object has no attribute 'credentials'
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 318, in post
    self.run_from_request()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 313, in run_from_request
    run(self.request.body)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 155, in run
    return func(*args, **kwds)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 198, in invoke_member
    return getattr(obj, membername)(*args, **kwargs)
  File "/base/data/home/apps/[redacted api endpoint]", line 21, in [redacted variable]
  File "/base/data/home/apps/[redacted]", line 188, in set ref.set(value)
  File "/base/data/home/apps/[redacted]/lib/firebase_admin/db.py", line 199, in set
    self._client.request('put', self._add_suffix(), json=value, params='print=silent')
  File "/base/data/home/apps/[redacted]/lib/firebase_admin/db.py", line 796, in request
    return super(_Client, self).request(method, url, **kwargs)
  File "/base/data/home/apps/[redacted]/lib/firebase_admin/_http_client.py", line 84, in request
    resp = self._session.request(method, self._base_url + url, **kwargs)
  File "/base/data/home/apps/[redacted]/lib/google/auth/transport/requests.py", line 197, in request
    self.credentials.before_request(
AttributeError: 'AuthorizedSession' object has no attribute 'credentials'
```

I am wondering if I am running into this issue:  https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/241 in `_http_client.py`

**Comment by hiranya911** [comment]
Doesn't look like something that can be addressed at this repo. I'd recommend reporting this at the google-auth library, or just asking around in StackOverflow.
