### ISSUE TITLE
AttributeError: 'module' object has no attribute '_GLOBAL_DEFAULT_TIMEOUT'

### ISSUE THREAD

**Issue by bazookon** [firebase/firebase-admin-python#215]
* Operating System version: Appengine Standard Enviroment
  * Library version: 2.13.0
  * Firebase Product: All

I can't fix it, works perfect in local server

## requirements.txt
```
firebase-admin
requests-toolbelt
python-dateutil

```

## Appengine stackdriver
```
 (/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 358, in __getattr__
    self._update_configs()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 294, in _update_configs
    self._registry.initialize()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 165, in initialize
    import_func(self._modname)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/appengine_config.py", line 9, in <module>
    import firebase_admin, os.path,logging
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/firebase_admin/__init__.py", line 23, in <module>
    from firebase_admin import credentials
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/firebase_admin/credentials.py", line 20, in <module>
    import google.auth
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/google/auth/__init__.py", line 19, in <module>
    from google.auth._default import default
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/google/auth/_default.py", line 30, in <module>
    import google.auth.transport._http_client
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/google/auth/transport/__init__.py", line 30, in <module>
    from six.moves import http_client
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/base/data/home/apps/s~vendemeapp/pos:1.413710077193240139/lib/six.py", line 82, in _import_module
    __import__(name)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/httplib.py", line 8, in <module>
    from python_std_lib import httplib
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/python_std_lib/httplib.py", line 725, in <module>
    class HTTPConnection:
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/python_std_lib/httplib.py", line 737, in HTTPConnection
    timeout=socket._GLOBAL_DEFAULT_TIMEOUT, source_address=None):
AttributeError: 'module' object has no attribute '_GLOBAL_DEFAULT_TIMEOUT'
```

And also sometimes

```
(/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py:263)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 358, in __getattr__
    self._update_configs()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 294, in _update_configs
    self._registry.initialize()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_lib/versions/1/google/appengine/api/lib_config.py", line 165, in initialize
    import_func(self._modname)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/3b44e98ed7fbb86b/python27/python27_dist/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/base/data/home/apps/s~vendemeapp/pos:1.413709980584117387/appengine_config.py", line 9, in <module>
    import firebase_admin, os.path,logging
  File "/base/data/home/apps/s~vendemeapp/pos:1.413709980584117387/lib/firebase_admin/__init__.py", line 23, in <module>
    from firebase_admin import credentials
  File "/base/data/home/apps/s~vendemeapp/pos:1.413709980584117387/lib/firebase_admin/credentials.py", line 20, in <module>
    import google.auth
  File "/base/data/home/apps/s~vendemeapp/pos:1.413709980584117387/lib/google/auth/__init__.py", line 19, in <module>
    from google.auth._default import default
  File "/base/data/home/apps/s~vendemeapp/pos:1.413709980584117387/lib/google/auth/_default.py", line 28, in <module>
    from google.auth import environment_vars
ImportError: cannot import name environment_vars
```

**Comment by hiranya911** [comment]
None of the errors are originating in the `firebase_admin` code, so we cannot really provide a fix. Make sure you have followed the additional setup instructions listed here: https://google-auth.readthedocs.io/en/latest/user-guide.html#the-app-engine-standard-environment

If the problem persists, please report at https://github.com/googleapis/google-auth-library-python where the `google.auth` code resides.
