### ISSUE TITLE
Assertion Error occurs after fresh reboot, goes away after a few minutes

### ISSUE THREAD

**Issue by charliesneath** [firebase/firebase-admin-python#234]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux raspberrypi 4.14.71+ #1145 Fri Sep 21 15:06:38 BST 2018 armv6l GNU/Linux
  * Firebase SDK version: 
```
Name: firebase-admin
Version: 2.14.0
Summary: Firebase Admin Python SDK
Home-page: https://firebase.google.com/docs/admin/setup/
Author: Firebase
Author-email: UNKNOWN
License: Apache License 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: cachecontrol, google-cloud-firestore, enum34, google-auth, requests, six, google-cloud-storage
Required-by: 
```
  * Firebase Product: database (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

I get an Assertion Error (pasted below) the first few times when running a script after rebooting my Raspberry Pi Zero W. After a few minutes, the error stops and I can interface with Firebase as expected. The error won't occur again until I reboot the Pi and run my script again.

This is problematic because the error prevents me from successfully running scripts when the Pi connects to wifi.

#### Steps to reproduce:

Reboot Pi and run script. Wait a few minutes and error doesn't occur.

#### Relevant Code:

Error output: 
```
Traceback (most recent call last):
  File "/home/pi/weatherbox/48_hour_forecast.py", line 136, in <module>
    render_forecast(args.location)
  File "/home/pi/weatherbox/48_hour_forecast.py", line 88, in render_forecast
    forecast_data_48_hours.append(darksky.get_time_machine_forecast(location, timestamp_today))
  File "/home/pi/weatherbox/darksky.py", line 83, in get_time_machine_forecast
    coordinates = get_lat_long(location_search)
  File "/home/pi/weatherbox/darksky.py", line 16, in get_lat_long
    saved_location = saved_location_ref.get()
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/db.py", line 219, in get
    return self._client.body('get', self._add_suffix(), params=params)
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/_http_client.py", line 93, in body
    resp = self.request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/db.py", line 882, in request
    return super(_Client, self).request(method, url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/firebase_admin/_http_client.py", line 84, in request
    resp = self._session.request(method, self._base_url + url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/transport/requests.py", line 198, in request
    self._auth_request, method, url, request_headers)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 320, in refresh
    assertion = self._make_authorization_grant_assertion()
  File "/usr/local/lib/python2.7/dist-packages/google/oauth2/service_account.py", line 314, in _make_authorization_grant_assertion
    token = jwt.encode(self._signer, payload)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/jwt.py", line 94, in encode
    signature = signer.sign(signing_input)
  File "/usr/local/lib/python2.7/dist-packages/google/auth/crypt/_cryptography_rsa.py", line 126, in sign
    message, _PADDING, _SHA256)
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 463, in sign
    algorithm, self, data
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/rsa.py", line 241, in _rsa_sig_sign
    assert errors[0].lib == backend._lib.ERR_LIB_RSA
AssertionError

```

**Comment by hiranya911** [comment]
Can't really provide any specific instructions to fix/debug, since the error is not raised by our code. Try asking this on StackOverflow or at https://github.com/pyca/cryptography.

**Comment by BullCheat** [comment]
I can confirm I am getting this too. Exact same configuration (Raspi Zero W).
It used to work with an older version (can't tell which).
Works on Raspi 3 though.
Seems to work after about a minute or two.

**Comment by charliesneath** [comment]
@BullCheat See this issue + discussion for details on what's happening here: https://github.com/pyca/cryptography/issues/4635

**Comment by BullCheat** [comment]
@charliesneath thank you so much! That did the trick.
For anyone that is not familiar with C or scripts and wants to use firebase at boot in python using rc.local:
Put this in `/home/pi/init_random.c`
`#include <stdio.h>
#include <assert.h>
#include <sys/syscall.h>
#include <unistd.h>


int main(void) {
    char dest[1];
    int n = syscall(SYS_getrandom, dest, sizeof(dest), 0);
    assert(n == 1);
    printf("completed\n");
}`
Do `cd && gcc -o init_random init_random.c`
Add `/home/pi/init_random && ` to your rc.local line.
For instance, if your rc.local contains `screen -dmS ...`, make it `/home/pi/init_random && screen -dmS ...`

**Comment by charliesneath** [comment]
@BullCheat Glad it was useful.

FWIW: I ended up removing Firebase from my project since I had a very limited reason for including it, but appreciate you detailing the steps above—will come in handy if I end up needing Firebase with this device in the future.
