### ISSUE TITLE
Importing db from firebase_admin problem

### ISSUE THREAD

**Issue by adwinang** [firebase/firebase-admin-python#254]
I am trying to import db to access the firebase data but it is not working

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/firebase_admin/db.py", line 33, in <module>
    from firebase_admin import _http_client
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/firebase_admin/_http_client.py", line 30, in <module>
    raise_on_status=False, backoff_factor=0.5)
TypeError: __init__() got an unexpected keyword argument 'status'

**Comment by hiranya911** [comment]
What is your `requests` version? We import urllib3 via requests so that's the version that need to be up-to-date.

**Comment by hiranya911** [comment]
This is in a new virtualenv sandbox:

```
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import firebase_admin
>>> firebase_admin.__version__
'2.15.1'
>>> import requests
>>> requests.__version__
'2.21.0'
>>> from firebase_admin import db
>>> firebase_admin.initialize_app(options={'databaseURL': 'https://test-project.firebaseio.com'})
<firebase_admin.App object at 0x7f9096ec0e90>
>>> ref = db.reference()
>>> ref
<firebase_admin.db.Reference object at 0x7f9096e5b650>
```

Somehow your code is getting wired to an old version of urllib3's `retry` module which doesn't support the `status` parameter.

**Comment by adwinang** [comment]
ok, somehow it is working all fine now, after I reinstalled the up to date version 2.15.1.
