### ISSUE TITLE
Firebase Storage File Upload : socket.timeout: The write operation timed out

### ISSUE THREAD

**Issue by jaideep99** [firebase/firebase-admin-python#467]
**Environment**
  * Operating System version:  Windows 10
  * Firebase SDK version: Firebase - 3.0.1
  * Library version: Firebase_admin(0.12.6)
  * Firebase Product: Storage

**Problem:**
On Uploading file using firebase_admin.storage through blob, socket connection timed out after 60secs. File size is 50Mb.

Here's the code:

```
def push_model(project,Uid,ptype):
    cred = credentials.Certificate('serviceAccountCredentials.json')
    app = firebase_admin.initialize_app(cred, {
        'storageBucket': 'abc-eb5f7.appspot.com'
    },name='storage')

    storage_bucket = storage.bucket(app=app)

    blob = storage_bucket.blob(Uid+"/"+project+".tflite")

    blob.upload_from_filename(project+".tflite")
```

**Error:**
```
Traceback (most recent call last):
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "C:\Users\jagat\AppData\Local\Programs\Python\Python36\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
```
The internet speed is 3.3Mbps. The file size is 50Mb. The connection broke after the 60secs. The same code worked earlier at 20Mbps.

How can this problem be resolved?

**Comment by hiranya911** [comment]
Storage Python client is developed at https://github.com/googleapis/python-storage. Please report the issue there.
