### ISSUE TITLE
Problem Installing firebase-admin Python 3.9

### ISSUE THREAD

**Issue by RaymonDev** [firebase/firebase-admin-python#499]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version:  Windows 10 Python 3.9
  * Firebase SDK version: _____
  * Library version: Latest
  * Firebase Product: Realtime database

#### Relevant Code:

Traceback (most recent call last):
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Propietario\AppData\Local\Programs\Python\Python39\Scripts\pip.exe\__main__.py", line 7, in <module>
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\commands\__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\req_command.py", line 20, in <module>
    from pip._internal.operations.prepare import RequirementPreparer
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 16, in <module>
    from pip._internal.distributions import (
  File "c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\distributions\__init__.py", line 1, in <module>
    from pip._internal.distributions.source import SourceDistribution
ImportError: cannot import name 'SourceDistribution' from 'pip._internal.distributions.source' (c:\users\propietario\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\distributions\source\__init__.py)

**Comment by lahirumaramba** [comment]
This looks like a known issue in `pip 20.0`:
- https://github.com/pypa/pip/issues/7620
- https://stackoverflow.com/questions/59842600/importerror-cannot-import-name-sourcedistribution-from-pip-internal-distrib
If you are on `pip version 20.0` try upgrading to a more recent version.
