### ISSUE TITLE
firebase admin SDK randomly raises an exception ServiceUnavailable: 503 Socket closed

### ISSUE THREAD

**Issue by codal-mharkhani** [firebase/firebase-admin-python#518]
* Operating System version: ubuntu 16.04
  * Firebase SDK version: 2.16.0
  * Python version: 2.7 (Django version : 1.9.4)
  * Firebase Product: Firestore

### Reproduce: Not sure, But maybe the issue occurs when we have more CRUD queries. 

```
Traceback (most recent call last):
  File "dir/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "dir/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "dir/utils.py", line 2107, in functionname
    functionname(db, contaxt)
  File "dir/utils.py", line 1960, in functionname
    for table in table_data:
  File "lib/python2.7/site-packages/google/cloud/firestore_v1beta1/query.py", line 744, in get
    for index, response_pb in enumerate(response_iterator):
  File "local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 81, in next
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
ServiceUnavailable: 503 Socket closed
```

#### Relevant Code:

```
def get_firebase_app_object():
    default_app = None
    file_name = "firebase-adminsdk.json"
    app_name = "dev"
    if settings.SENDBIRD_ENV == "prod":
        file_name = "firebase-adminsdk-prod.json"
        app_name = "application_name"

    try:
        if not firebase_admin._apps:
            creds_file_path = "{0}/{1}".format(dir, file_name)
            cred = credentials.Certificate(creds_file_path)
            default_app = firebase_admin.initialize_app(cred, name=app_name)
        else:
            default_app = firebase_admin.get_app(app_name)
    except Exception as e:
        print(e)

    return default_app

default_app = get_firebase_app_object()
db = firestore.client(app=default_app)

batch = db.batch()
#forloop will not contain morthan 100 element so it will not be more than limit
for i in a:
    some calculation 
    batch.set(ref, data)
    batch.update(ref, data)
batch.commit()
```

**Comment by hiranya911** [comment]
Please report Firestore issues directly at https://github.com/googleapis/python-firestore
