### ISSUE TITLE
Failed to import firestore

### ISSUE THREAD

**Issue by phaolin10** [firebase/firebase-admin-python#543]
Traceback (most recent call last):
  File "C:\Users\ismail\AppData\Local\Programs\Python\Python36\lib\site-packages\firebase_admin\firestore.py", line 22, in <module>
    from google.cloud import firestore # pylint: disable=import-error,no-name-in-module
  File "C:\Users\ismail\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\firestore.py", line 18, in <module>
    from google.cloud.firestore_v1 import __version__
  File "C:\Users\ismail\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\firestore_v1\__init__.py", line 30, in <module>
    from google.cloud.firestore_v1._helpers import GeoPoint
  File "C:\Users\ismail\AppData\Local\Programs\Python\Python36\lib\site-packages\google\cloud\firestore_v1\_helpers.py", line 38, in <module>
    from typing import (
ImportError: cannot import name 'NoReturn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/ismail/Desktop/MobileQuery/MobileQuery/api/app.py", line 4, in <module>
    from firebase_admin import firestore
  File "C:\Users\ismail\AppData\Local\Programs\Python\Python36\lib\site-packages\firebase_admin\firestore.py", line 28, in <module>
    raise ImportError('Failed to import the Cloud Firestore library for Python. Make sure '
ImportError: Failed to import the Cloud Firestore library for Python. Make sure to install the "google-cloud-firestore" module.

**Comment by phaolin10** [comment]
from flask import Flask, json, request, jsonify
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore
from google.cloud import firestore

app = Flask(__name__)


@app.route('/',methods=['GET'])
def show_all():
    cred = credentials.Certificate("./service_key.json")
    firebase_admin.initialize_app(cred)

    db = firestore.client()

    docs = db.collection('yellowtbs').where('tip_amount', "==", 2.26).stream()

    list = []

    for doc in docs:
        print("{} - {} \n".format(doc.id, doc.to_dict()))
        list.append(doc.id)
    return "a"


    
app.run()

here is my code. when I try to run it gives the error like that. How can I solve this problem

**Comment by hiranya911** [comment]
You probably need to upgrade your Python version. See following issues:

https://github.com/psf/black/issues/1666
https://github.com/beetbox/beets/issues/3143
https://stackoverflow.com/questions/65798315/importerror-cannot-import-name-noreturn-pytorch-on-macos-catalina

**Comment by phaolin10** [comment]
I tried but it doesn't work. 
Does anyone have a better idea ?

**Comment by hiranya911** [comment]
What exact version of Python did you try on?

**Comment by phaolin10** [comment]
I tried 3.6.0 and 3.7.0 and finally resolve this problem with python 3.9.2 version.

**Comment by Ppang0405** [comment]
Same when using python 3.10.1, using python 3.9.9 fixed it.
