### ISSUE TITLE
Random and Frequent "OSError" with Realtime Database listeners

### ISSUE THREAD

**Issue by amks1** [firebase/firebase-admin-python#588]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Debian GNU/Linux 10 (buster) 
  * Firebase SDK version: 5.1.0
  * Firebase Product: realtime database
  * Python version: 3.8.5
  * Pip version: 21.3.1

Note: It's running inside a docker container, the OS and python versions are from inside the container.

### [REQUIRED] Step 3: Describe the problem

Randomly getting `Connection aborted` and `OSError`s on my realtime DB listeners. Sometimes the listener stops working completely and I need to restart the container to get it to restart.
Here's the full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.8/site-packages/gevent/_ssl3.py", line 667, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/db.py", line 470, in _listen_with_session
    sse = _sseclient.SSEClient(url, session)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/_sseclient.py", line 97, in __init__
    self._connect()
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/_sseclient.py", line 110, in _connect
    self.resp = self.session.get(self.url, stream=True, **self.requests_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/google/auth/transport/requests.py", line 480, in request
    response = super(AuthorizedSession, self).request(
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_listeners_and_schedulers.py", line 33, in <module>
    consolemapmarkers_listen()
  File "/app/fmconsole/perpetual/listen_funcs.py", line 78, in consolemapmarkers_listen
    ref = rtdb.reference('console_map_markers').listen(parse_marker_event)              
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/db.py", line 375, in listen
    return self._listen_with_session(callback)
  File "/usr/local/lib/python3.8/site-packages/firebase_admin/db.py", line 473, in _listen_with_session
    raise _Client.handle_rtdb_error(error)
firebase_admin.exceptions.UnavailableError: Failed to establish a connection: ('Connection aborted.', OSError(0, 'Error'))
```

#### Steps to reproduce:

It happens frequently on its own, I don't know what causes it.

#### Relevant Code:

My app starts the listener like this:
```
 ref = rtdb.reference('console_map_markers').listen(parse_marker_event)
```

**Comment by lahirumaramba** [comment]
Looks like an `openssl` issue to me. Could you check your SSL version on your system by running `openssl version`?
Does your app use a proxy by any chance?

**Comment by lahirumaramba** [comment]
Closing this since there are no new updates. Feel free to reopen if you still have this issue. Thanks!
