### ISSUE TITLE
Problem installing firebase-admin in python3.6 windows10

### ISSUE THREAD

**Issue by clust3rsekt0r** [firebase/firebase-admin-python#82]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: __Windows10___
  * Firebase SDK version: __latest right now___
  * Library version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
I just try to install the python package and it give me an error.

#### Steps to reproduce:
1- pip install firebase-admin
What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
Collecting google-cloud-core<0.28dev,>=0.27.0 (from google-cloud-storage>=1.2.0->firebase-admin)
  Using cached google_cloud_core-0.27.1-py2.py3-none-any.whl
Collecting googleapis-common-protos>=1.3.4 (from google-cloud-core<0.28dev,>=0.27.0->google-cloud-storage>=1.2.0->firebase-admin)
  Using cached googleapis-common-protos-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 10, in <module>
        from setuptools.extern.six.moves import filter, filterfalse, map
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
        @_call_aside
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 3045, in _initialize_master_working_set
        dist.activate(replace=False)
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2577, in activate
        declare_namespace(pkg)
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2151, in declare_namespace
        _handle_ns(packageName, path_item)
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2091, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "c:\users\clust\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2120, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\clust\AppData\Local\Temp\pip-build-2qs9dsol\googleapis-common-protos\
```

**Comment by hiranya911** [comment]
This seems like an issue with pip/setuptools: https://github.com/pypa/setuptools/issues/885

Can you try with the latest tools?

**Comment by hiranya911** [comment]
I'm closing this since we haven't had an update in a while. If the issue continues to bother you, please reopen.
